### ISSUE TITLE
UserAudit

### ISSUE THREAD

**Issue by benmartel** [samrocketman/jenkins-script-console-scripts#5]
Has there been a change to jenkins or are you still able to run this script? When I tried to run it today it does not output a csv to the workspace nor seem to populate info in the console output for each user other than name and email address.

**Comment by samrocketman** [comment]
What plugins are you using?  Currently working on different Jenkins instances (both using LDAP) where one uses RBAC and the other uses project-based matrix for authorization.

It uses basic Jenkins APIs for determining access so it should work in a variety of setups.
